package net.gceylan.entities;

// Generated 26.Haz.2012 11:57:30 by Hibernate Tools 3.4.0.CR1

/**
 * OrnekTablo generated by hbm2java
 */
public class OrnekTablo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String tanim;
	private String aciklama;

	public OrnekTablo() {
	}

	public OrnekTablo(String tanim, String aciklama) {
		this.tanim = tanim;
		this.aciklama = aciklama;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTanim() {
		return this.tanim;
	}

	public void setTanim(String tanim) {
		this.tanim = tanim;
	}

	public String getAciklama() {
		return this.aciklama;
	}

	public void setAciklama(String aciklama) {
		this.aciklama = aciklama;
	}

}
